packages:
  - NodeJS-smartAPI
  - UI-components
  - Nodejs-LudiCloud
  - NodeJS-LudiCloud-API
  - ReactJS-Ludicloud
  - NodeJS-smartPeople-API
  - ReactJS-smartPeople
  - NodeJS-smartLibrary
  - ReactJS-smartLibrary
  - eslint-config
  - stylelint-config
  - prettier-config
  - bundle-config
  - tsconfig
  - git-hooks-config
